- name: Create isucari directory
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/isucari
    state=directory

- name: Deploy isucari
  become: yes
  synchronize:
    src: ../../../../webapp/
    dest: /home/isucon/isucari/webapp
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=public/upload"

- name: Download image assets
  become: yes
  block:
    - file:
        path: /home/isucon/isucari/webapp/public/upload
        state: directory
    - unarchive:
        remote_src: yes
        src: https://github.com/isucon/isucon9-qualify/releases/download/v2/initial.zip
        dest: /home/isucon/isucari/webapp/public/upload
        creates: /home/isucon/isucari/webapp/public/upload/0a0b7d9d02859f66d171e4d2337aec2d.jpg
        extra_opts:
          - -j

- name: Chown isucon
  become: yes
  file:
    dest: /home/isucon/isucari
    owner: isucon
    group: isucon
    mode: 0755
    recurse: yes
